const USER_LOGIN = "USER_LOGIN";
const USER_REGISTER = "USER_REGISTER";
const USER_LOGOUT = "USER_LOGOUT";
const USER_DELETE = "USER_DELETE";
const GET_USER_BY_RNO = "GET_USER_BY_RNO";
const ADD_NEW_EVENT = "ADD_NEW_EVENT";
const DELETE_EVENT = "DELETE_EVENT";

const MARK_ATTENDANCE = "MARK_ATTENDANCE";
const ADD_MENTOR_NAME = "ADD_MENTOR_NAME";
const RESET_USER_RNO = "RESET_USER_RNO";
export {
  USER_LOGIN,
  USER_REGISTER,
  USER_LOGOUT,
  USER_DELETE,
  ADD_NEW_EVENT,
  DELETE_EVENT,
  MARK_ATTENDANCE,
  ADD_MENTOR_NAME,
  GET_USER_BY_RNO,
  RESET_USER_RNO,
};
